### ISSUE TITLE
Switchboard crashes with DiGImend driven tablet

### ISSUE THREAD

**Issue by yahoo1999** [elementary/switchboard-plug-wacom#11]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Switchboard crashes when trying to access Wacom settings when wacom compatible tablet driven by [DIGImend kernel driver](https://github.com/DIGImend/digimend-kernel-drivers) is connected. In my case it's Gaomon S620 (ID 256c:006d).

### To Reproduce
1. Install DIGImend kernel driver
2. Connect Gaomon S620 (or possibly any other xsetwacom compatible tablet, that isn't in fact Wacom)
3. Try to access Wacom settings in Switchboard
4. Instant app crash

### Expected behavior
Surely Gaomon S620 is non-standard graphics tablet but as it's xsetwacom compatible when used with DiGImend driver I was hoping Switchboard Wacom plugin will be able to set it up. Even if it's not (and won't be in future) compatible it should throw according message instead of crashing.

### Logs

```
#0  0x00007fffd4a0113e in wacom_backend_wacom_device_construct (object_type=93825002907536, device=0x555556170700, error=0x7fffffffd070) at /home/yahoo_1999/compileroom/wacomGUI/switchboard-plug-wacom/src/Backend/WacomDevice.vala:54
#1  0x00007fffd4a0129c in wacom_backend_wacom_device_new (device=0x555556170700, error=0x7fffffffd070)
    at /home/yahoo_1999/compileroom/wacomGUI/switchboard-plug-wacom/src/Backend/WacomDevice.vala:44
#2  0x00007fffd4a0bc23 in wacom_plug_add_known_device (self=0x5555559e42e0, d=0x555556170700)
    at /home/yahoo_1999/compileroom/wacomGUI/switchboard-plug-wacom/src/Plug.vala:167
#3  0x00007fffd4a0b121 in wacom_plug_real_get_widget (base=0x5555559e42e0)
    at /home/yahoo_1999/compileroom/wacomGUI/switchboard-plug-wacom/src/Plug.vala:107
#4  0x000055555555b0f1 in  ()
#5  0x00007ffff7904285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7904650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7904962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff6927a25 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x000055555555d51c in  ()
#10 0x00007ffff72d510d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff72e7de8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff72f0715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff72f112f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff75bbb95 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff75bbda6 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x000055555555d803 in switchboard_main ()
#17 0x00007ffff5e93b97 in __libc_start_main (main=
    0x55555555acc0 <main>, argc=1, argv=0x7fffffffdc28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc18) at ../csu/libc-start.c:310
#18 0x000055555555acfa in _start ()
```

## Platform Information
![OS About tab](https://i.imgur.com/uu2JAbO.png)

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context
I'm well aware that it may be not neccesairly a bug, just a pure incompatibility. It would be great to have an ability to configure non-standard xsetwacom compatible tablets as well though.

**Comment by peteruithoven** [comment]
There is a big change #17 will fix this issue.

**Comment by peteruithoven** [comment]
There are 4 issues on crashing, which probably have the same cause. Could you try the latest version and re-open the issue when you're still experiencing the issue?
