### ISSUE TITLE
Crashes on Wacom Ctl4100 

### ISSUE THREAD

**Issue by BrunoNogueiraBruno** [elementary/switchboard-plug-wacom#14]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Switchboard crashes when I plugged my Wacom Ctl4100

### Expected behavior
Wacom plug opens

### Logs

- [X] I'm using the latest version from git that I've manually compiled

**Comment by peteruithoven** [comment]
There is a big change https://github.com/elementary/switchboard-plug-wacom/pull/17 will fix this issue.

**Comment by peteruithoven** [comment]
There are 4 issues on crashing, which probably have the same cause. Could you try the latest version and re-open the issue when you're still experiencing the issue?
