### ISSUE TITLE
Support Wacom One CTL-472

### ISSUE THREAD

**Issue by igordsm** [elementary/switchboard-plug-wacom#20]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I plugged my Wacom One CTL-472, but the settings page shows a message saying that there are no tablets available. 

`xsetwacom --list devices` shows the following output:

```
Wacom One by Wacom S Pen stylus 	id: 13	type: STYLUS    
Wacom One by Wacom S Pen eraser 	id: 14	type: ERASER    
```

`libwacom-list-local-devices` shows the following output
```
[Device]
Name=One by Wacom (small)
DeviceMatch=usb:056a:037a;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Styli=0xfffff;0xffffe;

[Features]
Reversible=true
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=0
---------------------------------------------------------------
```

![Screenshot from 2020-08-06 17-46-57](https://user-images.githubusercontent.com/221446/89581504-7c4fcb00-d80d-11ea-8701-88dcdc3ebd66.png)

### To Reproduce
1. Connect a Wacom One 
2. Go to the plug page
3. See message "No tablets Available"

### Expected behavior

A settings page to configure the tablet

## Platform Information

![Screenshot from 2020-08-06 17-52-59](https://user-images.githubusercontent.com/221446/89581633-b15c1d80-d80d-11ea-8b6b-26b8dddac14d.png)

- [X] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by davidmhewitt** [comment]
Can you run `libwacom-list-local-devices` with your tablet connected and let me know what the output is (if any) ?

**Comment by igordsm** [comment]
@davidmhewitt Sure. I have updated the description.

**Comment by davidmhewitt** [comment]
Can you check if `xserver-xorg-input-wacom-hwe-18.04` is installed, and install it if not?

Because this isn't officially release for elementary OS yet, it may not have all of its dependencies installed.

**Comment by igordsm** [comment]
`xserver-xorg-input-wacom-hwe-18.04` is installed and the tablet is working fine in apps like Krita and Gimp. However, it is not detected by the plug.

**Comment by davidmhewitt** [comment]
Thanks, at least we've ruled out the obvious stuff.

I haven't looked at this plug in a while, but I'll try and find some time to have a look at it soon and get back to you. I imagine I'll need to add some logging to it and then ask you to try again so we can see where it's giving up on your device.

**Comment by igordsm** [comment]
@davidmhewitt So I have gone through the code and have found some things: 

1. `DeviceManagerX11.list_devices` finds two devices of type `TABLET`: `Wacom One by Wacom S Pen stylus` and `Wacom One by Wacom S Pen eraser`
2. `WacomToolMap.list_tools` returns a list of size 0 for both devices. 

I do not have a working tablet to compare these with a setup that works, but this may help.

**Comment by igordsm** [comment]
More information: at `Wacom.Plug.update_current_page` there is no device with type `PAD`. Both devices listed above have type `TABLET` (`dev_type == 8`). : Wacom One tablets do not have buttons, only the pen with two buttons. It seems this could be the issue, right?

**Comment by igordsm** [comment]
Ok, now I am getting some progress:

![Screenshot from 2020-08-06 21-37-50](https://user-images.githubusercontent.com/221446/89596273-225efd80-d82d-11ea-85df-2bc5e3053507.png)

I can get it to "work" by accepting `Backend.Device.DeviceType.TABLET` as well. It then selects the `Wacom One by Wacom S Pen stylus` device and the tablet view works correctly: I can set both relative/absolute tracking as well as left-handed mode. 

However, the stylus view still crashes horribly and I am not sure yet why. It seems that some device hardware_id or serial is not being received correctly, which means no tools are found. Well, progress is progress!

**Comment by igordsm** [comment]
@davidmhewitt  I got some progress in this issue in PR #21 . 

I'm doing some experiments with Tool detection, but I always get `serial=1` and `hardware_id=2` in my tests and this fails in `wacom_db.get_tool_for_id`. The GUI "works" fine with `serial=0, id=0`, but it does not affect the tablet at all. It this expected?

**Comment by JMoerman** [comment]
@igordsm I don't know If you are still interested in this issue, but can you try running the following script?

```
#!/bin/bash

for d in /sys/bus/usb/devices/*; do 
  if [ -r "$d/idVendor" ]; then
    idVendor=`cat $d/idVendor` 
    idProduct=`cat $d/idProduct` 
    if [ "$idVendor" = "056a" -a "$idProduct" = "00fa" ]; then
      echo 0 > "$d/authorized"
      echo 1 > "$d/authorized"
    fi
  fi
done
```

Where you should replace `00fa` with the product ID returned by `lsusb`, for me it was `00f4`:
```
Bus 003 Device 006: ID 056a:00f4 Wacom Co., Ltd DTK-2400 [Cintiq 24HD] tablet
```

There seems to be a kernel issue (linux >= 4.15) with the USB subsystem disliking Wacom devices. If the script above works the issue you are facing isn't really an elementary OS issue, just a Linux issue in general.
Source: https://github.com/linuxwacom/input-wacom/issues/34

This workaround brings my Wacom Cintiq 24HD to life on a daily build of elementary OS 6. I was curious if my Wacom issues would be fixed here but just like on 5 it is currently broken. I might bissect the issue at some point, but currently I don't feel it is the best way to spend my time. Wacom support on Linux has always been mediocre at best in my experience.

**Comment by igordsm** [comment]
@davidmhewitt My wacom tablet works fine overall (pressure sensitivity and all), it just doesn't get detected by the plug. It seems like the plug expects different hardware from what I have and fails the detection even though some information is received by it (pencil and erase tools, no pad). However, since I do not have a tablet that gets detected correctly I'm not sure if my proposed fix is OK. 

I can test if results change in Odin if you think it is worth it.

**Comment by davidmhewitt** [comment]
@igordsm Sorry for not getting back to you sooner on this.

Could you try out the [better device detection branch](https://github.com/elementary/switchboard-plug-wacom/compare/better-device-detection?expand=1) and let me know if that works for you?
